/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 MiniJesusSwing.gltf --transform 
Files: MiniJesusSwing.gltf [8.04MB] > MiniJesusSwing-transformed.glb [352.22KB] (96%)
*/

import React, { useRef, useEffect, Suspense  } from 'react'
import { useGLTF, Html, useProgress } from '@react-three/drei'
import MarioModel from "./MarioModel";
import Guitar from './Guitar';
import { styled } from 'styled-components'

export default function Mario(props) {
  const group = useRef()
  const child1 = useRef();
  const child2 = useRef();

  useEffect(() => {
    // actions[names[0]].play();
  }, [])

  const handleParentFunction = () => {
    // Do something in the parent component
    console.log("Function called from the parent component!");

    child1.current.playAnim();
    child2.current.playAnim();
  };


  return (
    <group ref={group} {...props} dispose={null} onClick={(e) => handleParentFunction()}>
        <MarioModel ref={child1} callParentFunction={handleParentFunction}  />
        <Guitar ref={child2} callParentFunction={handleParentFunction} />
    </group>
  )
}

useGLTF.preload('/Models/Mario/Guitar-transformed.glb')
// useGLTF.preload('/MiniJesusSwing-transformed.glb')
